# $NetBSD$

DISTNAME=	dav1d-0.8.1
CATEGORIES=	multimedia
MASTER_SITES=	https://code.videolan.org/videolan/dav1d/-/archive/0.8.1/

MAINTAINER=	apamment@yandex.com
HOMEPAGE=	https://code.videolan.org/videolan/dav1d/-/archive/0.8.1
COMMENT=	Small and fast AV1 decoder
LICENSE=	2-clause-bsd

.include "../../devel/meson/build.mk"
.include "../../mk/bsd.pkg.mk"
