# $NetBSD$

DISTNAME=	libsysinfo-0.0.3
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_GITHUB:=bsdimp/}
GITHUB_TAG=     e535d95d1598932a0084a027402104d6e0276479

MAINTAINER=	apamment@yandex.com
HOMEPAGE=	https://github.com/bsdimp/libsysinfo 
COMMENT=	FreeBSD version of libsysinfo
LICENSE=	modified-bsd

.include "../../mk/bsd.pkg.mk"
